# This is workflow to build docker images
name: build

on:
  push:
    branches: [ "master" ]
    # Only kick workflow if implementation or configuration updates
    paths-ignore:
      - 'document/**'
  pull_request:
    # Only kick workflow if implementation or configuration updates
    branches: [ "master" ]
    paths-ignore:
      - 'document/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
    - name: Build SRT Prometheus Exporter and Samples
      run: sudo ./scripts/build-verification.sh
